name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  workflows: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Replace ENV in HTML
        run: |
          sed -i 's/__FLARELANE_PROJECT_ID__/${{ secrets.FLARELANE_PROJECT_ID }}/g' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: .
